<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <SupportedUICultures>en-US</SupportedUICultures>
    <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-SecureAppLocker.Service-e67a631e-396d-42cc-9c24-cdc23fb282c2</UserSecretsId>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>icon.ico</ApplicationIcon>

    <!-- Metadata & Copyright -->
    <Company>Osman Onur Koç</Company>
    <Product>SecureAppLocker Service</Product>
    <AssemblyTitle>SecureAppLocker Background Service</AssemblyTitle>
    <Description>Background execution and lock enforcement service for SecureAppLocker</Description>
    <Copyright>www.osmanonurkoc.com</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
    <PackageReference Include="Microsoft.Win32.SystemEvents" Version="10.0.10" />
    <PackageReference Include="System.IO.Pipes.AccessControl" Version="5.0.0" />
    <PackageReference Include="System.Management" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SecureAppLocker.Core\SecureAppLocker.Core.csproj" />
  </ItemGroup>
</Project>
